version: '3'


services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d/local.conf
    depends_on:
      - app
  app:
    build: .
    command: python manage.py runserver

